### ISSUE TITLE
请问进行微调的话，大概需要多少数据？

### ISSUE THREAD

**Issue by stereomatchingkiss** [yujiangpu20/PEL4VAD#11]
如题，假设我要检测“不正常驾驶行为(例如逆向行驶，急速180度转弯etc)”，大约需要多少资料？谢谢

**Comment by yujiangpu20** [comment]
The UCF-crime training set contains 1610 videos, while XD-Violence contains 3954. The least is the ShanghaiTech dataset, which contains 238 training samples. FYI.
