### ISSUE TITLE
About Ten Crop Features

### ISSUE THREAD

**Issue by kienptitit** [yujiangpu20/PEL4VAD#13]
Congratulations on the interesting work! 
I have a question regarding the dataset. In some previous works, I noticed that the ten crop features are usually concatenated into [T, 10, 1024]. However, it seems that in your code, the desired shape is [T, 1024]. Could you please explain this to me, or have I misunderstood any concepts? 
Thank you very much.

**Comment by kienptitit** [comment]
Oh, sorry !!!
My mistake, I figure it out.

**Comment by jpainam** [comment]
For someone wondering why the feature from the README are not `10-cropped`

READ  https://github.com/Roc-Ng/DeepMIL  


_they oversampled each video frame with the “10-crop” augment, “10-crop” means cropping images into the center, four corners, and their mirrored counterparts. _0.npy is the center, _1~ _4.npy is the corners, and _5 ~ _9 is the mirrored counterparts._
