### ISSUE TITLE
关于论文的图7的生成问题

### ISSUE THREAD

**Issue by jiaqiyang874** [yujiangpu20/PEL4VAD#14]
作者您好，拜读了您的论文后，论文图7的可视化效果吸引到了我，如果方便的话，想请教一下可视化图片是如何生成的

**Comment by yujiangpu20** [comment]
It is a t-SNE visualization using sklearn and matplotlib library. Please refer to [https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html](url).
