### ISSUE TITLE
你好，我想问下如果我不用PEL模块，我要怎么复现其他部分呢？

### ISSUE THREAD

**Issue by modadundun** [yujiangpu20/PEL4VAD#16]
你好，我想问下如果我不用PEL模块，我要怎么复现其他部分呢？

**Comment by yujiangpu20** [comment]
Just simply comment out the PEL part in the training code.

**Comment by modadundun** [comment]
十分感谢您能够在这么晚的回复，谢谢！您的代码我最近基本搞懂了，但是相似性矩阵模块我不是很理解，您构建了一个等差数列，计算相似性矩阵，最后输出是局部特征，而这个模块的输入是(shape(0),shape(1))，到底是如何得到不同时间尺度的局部特征呢？您这一点是如何实现的呢，我就这一个问题了，十分感谢如果您能看到并回复的话！！！

**Comment by yujiangpu20** [comment]
If you are referring to the local mask, it is used for the self-attention operation of the current segment i with segments within the local window [i-w/2, i+w/2]. We did not consider multi-scale temporal modeling.
