### ISSUE TITLE
Questions about the dataset.

### ISSUE THREAD

**Issue by LucasChenLC** [yujiangpu20/PEL4VAD#3]
Dear author, thank you  for your excellent work!

I was wandering where do you get the training annotation file of ShanghaiTech Campus dataset? For I see that the original dataset is unsupervised, providing no annotation files during training. If you obtain it from other repo or paper. Can you please paste the link? 

That will be great help.

**Comment by Aaron-Pu** [comment]
Please refer to this repo: https://github.com/jx-zhong-for-academic-purpose/GCN-Anomaly-Detection.


Best,
Yujiang

---- Replied Message ----
From Lucas Chen ***@***.***> Date 08/04/2023 13:28 To Aaron-Pu/PEL4VAD ***@***.***> Cc Subscribed ***@***.***> Subject [Aaron-Pu/PEL4VAD] Questions about the dataset. (Issue #3)  

Dear author, thank you for your excellent work!
I was wandering where do you get the training annotation file of ShanghaiTech Campus dataset? For I see that the original dataset is unsupervised, providing no annotation files during training. If you obtain it from other repo or paper. Can you please paste the link?
That will be great help.

**Comment by LucasChenLC** [comment]
> Please refer to this repo: https://github.com/jx-zhong-for-academic-purpose/GCN-Anomaly-Detection. Best, Yujiang
> […](#)
Thank you very much!
I think there is only the train and test split in this rope. Can you please tell how you get the labels or a notions of the train split? Including 0/1 label for weakly supervised training and prompt label like 'cycling' for prompt learning.

**Comment by Aaron-Pu** [comment]
The original dataset contains 300 normal training samples and 107 abnormal test samples, you can refer to this link: https://svip-lab.github.io/dataset/campus_dataset.html. In addition, the annotations used for Prompt learning were manually labeled, as mentioned in our paper.

**Comment by LucasChenLC** [comment]
Thank you very much.
