### ISSUE TITLE
关于用cpu训练要修改哪些代码

### ISSUE THREAD

**Issue by modadundun** [yujiangpu20/PEL4VAD#4]
作者您好，我的电脑只有cpu,当我配好环境修改需要用到cuda的换成cpu后，发现抱错AssertionError: Torch not compiled with CUDA enabled。我猜测有遗漏可以告知要修改哪些代码让他可以用CPU跑吗？十分感谢！

**Comment by Aaron-Pu** [comment]
请尝试将代码中与CUDA相关的部分注释或删除，但仅用CPU训练难以保证程序运行，我们在单卡A40上训练UCF-Crime数据集大约占用10G显存。

**Comment by modadundun** [comment]
谢谢，我发现有个地方我没删除。现在可以运行。那是否可以添加代码让他只接受少量的数据呢？目前还是本科手上的确只有CPU。十分感谢！

**Comment by Aaron-Pu** [comment]
数据量是一方面因素，可以通过batch size调节，另一方面与视频长度相关。并行处理长时序列需要消耗较大显存，这取决于输入的视频长度。
