### ISSUE TITLE
About calculation of AUC

### ISSUE THREAD

**Issue by s10400015** [yujiangpu20/PEL4VAD#5]
感謝你的傑出的貢獻

我想請教有關於最後的AUC計算是以snippet level當作frame level嗎

若不是想請問計算方式為何

非常感謝

**Comment by yujiangpu20** [comment]
是的，每一个snippet是由16帧的滑动窗口采样获得，因此最后计算AUC值时将每个snippet的分数复制16份分配给对应帧。
