### ISSUE TITLE
about random seed

### ISSUE THREAD

**Issue by s10400015** [yujiangpu20/PEL4VAD#8]
作者你好

首先先感謝先前的問題解惑，目前能正常訓練CLIP model了

如同README中提到的會因為訓練使用的機器不同，得到不同的result

我使用的是2張Nvidia 2080Ti 在三個數據集上復現的結果分別是UCF 85.74/XD 84.46/SH 97.92

其中在UCF及XD上都差了1%左右

目前嘗試修改random seed去達到好一點的result

想請問作者是如何選擇這些random seed的

**Comment by yujiangpu20** [comment]
These settings are what works best on our machines, you can try any seed to see the effect.

**Comment by s10400015** [comment]
I'll try that. Thanks for replying and wish you have a nice vacation

**Comment by s10400015** [comment]
Sorry to bother you again, but I tried my best seed to train and still can't show the performance on paper.
I think it might be caused by the version of Cuda.
Now I train these codes in Ubuntu 22.04  NVIDIA-SMI 450.66  Driver Version: 450.66  CUDA Version: 11.0
What's the environment that you train in? like Ubuntu 22.04/20.04
Best Regards
