### ISSUE TITLE
About the selection of 5 Relations

### ISSUE THREAD

**Issue by santiagosilas** [yujiangpu20/PEL4VAD#9]
Hi Yujiang,

I have a question about your prompt construction procedure.
How did you select 5 relations from the 12 most common relations ?
Did you use some specific procedure ? I did not find this instruction on code or paper.
I could notice that shanghaitech, ucfcrime and xd use the same 5 relations.

Thanks for share your source code.

Thanks in advance.

**Comment by yujiangpu20** [comment]
We explained the selection method in Prompt Construction subsection. The top five items with the highest occurrence frequency across all categories are chosen as the retrieval relations. Moreover, the selections in ShanghaiTech differ from other datasets. For more details, please refer to the supplementary materials.
